### ISSUE TITLE
SDR?

### ISSUE THREAD

**Issue by bdwyer2** [jeeftor/colorado-springs-utilities-scraper#1]
I've been trying to pull data off my CSU meter with an SDR dongle but haven't had any luck (https://github.com/allangood/rtlamr2mqtt). Have you tried playing around with SDR?

**Comment by dmbreakey** [comment]
Apologies; I haven't had much chance to dig into this. I did try running it, and so far I can't get it to work for me.

I've also been investigating whether Scrapy might be a better solution, but right now that one's twisting my brain into knots.

As for SDR, that looks different from what I've found on [this page](https://www.home-assistant.io/docs/energy/electricity-grid/)? Specifically something called [Home Assistant Glow](https://github.com/klaasnicolaas/home-assistant-glow).

Do you happen to know if the CSU meters might support that? I haven't gone into my crawlspace to check yet.

**Comment by bdwyer2** [comment]
My water meter is a Sensus CellNet M510C-D1-3W-X-T. The fact that it's called "CellNet" makes me wonder if they are collecting data over the cell network.

My gas meter is an American Meter Company AC-250.

Most of my neighbors have the Itron meters but I'm on the new CSU smart meter.

I haven't been able to find much by Googling and running the SDR dongle for 24 hours didn't capture anything

**Comment by jeeftor** [comment]
So I have solar and can read energy from that and a flume for water. So I really only care about gas. Haven’t had much time to circle back to this

**Comment by jeeftor** [comment]
I updated the readme a little bit -> but basic idea is I kinda copied the flow of URLs when you log in to hit the download button. 

Its pretty wonky what you need to pass into the final forms - and I think the final call has some hardcodes..

(I'm closing this - but feel free to open another issue ... if you want ) ... if you feel like making progress. This is semi-on the back burner right now as I'm more focused on my intellifire4py integration :) 

But when its not longer fire place season this will maybe be more compelling work :)
